### ISSUE TITLE
Noticed some console warnings for unique key prop on mapped items

### ISSUE THREAD

**Issue by bjonesy** [tayiorbeii/gatsby-demo-blog-code#1]
First off I wanted to say thanks for the video on egghead.io!  I appreciate it and it was the first time I've seen Gatsby.   I must say it is pretty awesome and will def be using it somewhere.  I noticed some console warnings for adding a key on the mapped posts and post tags.  I have a small PR I would like to open where I add an index to the mapped items and use the index as the unique key prop.  I would like to contribute but if you feel this is something irrelevant then I will close this out.

Thanks!

**Comment by tayiorbeii** [comment]
Hi @bjonesy, sorry for the delay! Feel free to open a PR :)

**Comment by bjonesy** [comment]
@tayiorbeii Thanks!
