### ISSUE TITLE
Include Links to Next and Previous Gatsby Blog Posts - sort order?

### ISSUE THREAD

**Issue by spences10** [tayiorbeii/gatsby-demo-blog-code#2]
Thanks so much for this information @tayiorbeii 

I have been playing around with Gatsby on and off for a while and the egghead.io videos really helped tie it all together.

The reason for the issues is I have implemented the **Include Links to Next and Previous Gatsby Blog Posts** in my blog, pretty much exactly as in this example, however, I'm not getting the same expected results, here is a list of posts from my index page:
![image](https://user-images.githubusercontent.com/234708/34603958-fbfee078-f1fd-11e7-99b2-d0c3782c5a9e.png)

Using the following GQL query:

```js
export const query = graphql`
  query IndexQuery {
    allMarkdownRemark(
      sort: { order: DESC, fields: [frontmatter___date] }
      filter: { frontmatter: { published: { eq: true } } }
    ) {
      totalCount
      edges {
        node {
          excerpt(pruneLength: 250)
          id
          frontmatter {
            title
            date(formatString: "DD MMMM YYYY")
            path
            tags
            excerpt
          }
        }
      }
    }
  }
`
```

So if I go to the bottom of the most recent post there **Git ` — allow-unrelated-histories`** where the `blog-post.js` template is used with the following GQL statement:
```js
export const pageQuery = graphql`
  query BlogPostByPath($path: String!) {
    markdownRemark(frontmatter: { path: { eq: $path } }) {
      html
      frontmatter {
        title
        date(formatString: "DD MMMM YYYY")
        path
        tags
        excerpt
      }
    }
  }
`
```
My next and previous navs don't seem to map to what is on the main `index.js` page:

![image](https://user-images.githubusercontent.com/234708/34605592-1a36e88c-f204-11e7-86f2-b969db438b88.png)

Here is the template I'm using for prev and next:

```js
const Template = ({ data, location, pathContext }) => {
  const { markdownRemark: post } = data
  const { frontmatter, html } = post
  const { title, date, tags } = frontmatter
  const { next, prev } = pathContext

  return (
    <div>
      <Helmet title={`${title} - blog.scottspence.me`} />
      <Title>{title}</Title>
      <TitleDate>{date}</TitleDate>

      <ContentWrapper dangerouslySetInnerHTML={{ __html: html }} />

      <NavWrapper>
        <NavP>
          {prev && (
            <Link to={prev.frontmatter.path}>
              Previous: {prev.frontmatter.title}
            </Link>
          )}
        </NavP>
        <NavP>
          {next && (
            <Link to={next.frontmatter.path}>
              Next: {next.frontmatter.title}
            </Link>
          )}
        </NavP>
      </NavWrapper>
      <TagsContainer tags={post.frontmatter.tags} />
    </div>
  )
}
```

Are you able to give any advice on how I can debug this? 

Thanks

**Comment by tayiorbeii** [comment]
@spences10 Glad to hear the course was helpful! 
Reading over your queries, they look the same as what I have... out of curiosity, what is your post directory structure like?

Mine are `src/pages/YYYY-MM-DD-slug` in case yours are different?

**Comment by spences10** [comment]
Hey @tayiorbeii my file structure _was_ the same `src/pages/YYYY-MM-DD-slug` when I noticed this behaviour.

I've since changed structure slightly to include a year `src/pages/YYYY/YYYY-MM-DD-slug` but like I mentioned I noticed this before doing that.

**Comment by tayiorbeii** [comment]
The only other thing I can think of is check to see if you have the exact same frontmatter in each of your posts, even if you aren't using it (like `excerpt: ''`)

**Comment by spences10** [comment]
🤔 
Ok @tayiorbeii, thanks, I've had a look and frontmatter all seems to be consistent with each other, I think I'm going to remove them all, add back three then take it from there.

I probably should have done that before logging this issue 🙃

**Comment by tayiorbeii** [comment]
Sorry I couldn't be of more help. I know that "works on my machine" isn't
always the best response, but it is a familiar phrase to devs! :)

**Comment by spences10** [comment]
Hehe, np, I myself have said the same thing many a time 😁 I'll post back here if I manage to wok it out

Thanks again @tayiorbeii 👌

**Comment by spences10** [comment]
It was `gatsby-node.js`

![image](https://user-images.githubusercontent.com/234708/34781124-edb554ac-f61c-11e7-9519-35072d1287b5.png)

```js
exports.createPages = ({ boundActionCreators, graphql }) => {
  const { createPage } = boundActionCreators
  const blogPostTemplate = path.resolve('src/templates/blog-post.js')

  // returns promise that will start with this graphql query
  return graphql(`
    {
      allMarkdownRemark(
        sort: { order: ASC, fields: [frontmatter___date] }
        limit: 1000
      ) {
        edges {
          node {
            html
            id
            frontmatter {
              date
              path
              title
              excerpt
              tags
            }
          }
        }
      }
    }
  `).then(result => {
    if (result.errors) {
      return Promise.reject(result.errors)
    }

    const posts = result.data.allMarkdownRemark.edges

    createTagPages(createPage, posts)

    // Create pages for each markdown file.
    posts.forEach(({ node }, index) => {
      const prev = index === 0 ? false : posts[index - 1].node
      const next =
        index === posts.length - 1 ? false : posts[index + 1].node
      createPage({
        path: node.frontmatter.path,
        component: blogPostTemplate,
        context: {
          prev,
          next
        }
      })
    })

    return posts
  })
}
```

Happy to close now @tayiorbeii 👍

**Comment by tayiorbeii** [comment]
Glad you got it worked out @spences10 !
